<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { useRoute } from "vue-router"; import { api } from "../api"; import { Download, Plus, Save, Trash2, Type } from "lucide-vue-next";
type Element={id:string;type:"text"|"shape";text:string;x:number;y:number;w:number;h:number;fontSize:number;color:string;fill?:string;bold:boolean}; type Slide={id:string;title:string;notes:string;elements:Element[]}; type Version={id:string;version:number;slideJson:{title:string;slides:Slide[]};createdAt:string}; type Pres={id:string;title:string;versions:Version[]};
const route=useRoute();const data=ref<Pres|null>(null);const current=ref<Version|null>(null);const slideIndex=ref(0);const selected=ref<string|null>(null);const saving=ref(false);
const slide=computed(()=>current.value?.slideJson.slides[slideIndex.value]);
async function load(){const result=await api<Pres>(`/presentations/${route.params.id}/versions`);data.value=result;current.value=result.versions[0]?structuredClone(result.versions[0]):null;}
function selectVersion(v:Version){current.value=structuredClone(v);slideIndex.value=0;selected.value=null;}
function addText(){slide.value?.elements.push({id:crypto.randomUUID(),type:"text",text:"新文本",x:1,y:1,w:4,h:.6,fontSize:20,color:"111827",bold:false});}
function removeElement(){if(!slide.value||!selected.value)return;slide.value.elements=slide.value.elements.filter(e=>e.id!==selected.value);selected.value=null;}
async function save(){if(!current.value||!data.value)return;saving.value=true;try{const v=await api<Version>(`/presentations/${data.value.id}/versions`,{method:"POST",body:JSON.stringify({prompt:"网页编辑",document:current.value.slideJson})});await load();selectVersion(v);}finally{saving.value=false;}}
function download(){if(current.value)window.open(`/api/presentation-versions/${current.value.id}/download`,`_blank`);}
onMounted(load);
</script>
<template><div class="ppt-page" v-if="current&&data"><header class="ppt-toolbar"><div><h2>{{data.title}}</h2><span>版本 {{current.version}}</span></div><div><button @click="addText"><Plus :size="16"/>文本</button><button :disabled="!selected" @click="removeElement"><Trash2 :size="16"/>删除</button><button @click="download"><Download :size="16"/>下载</button><button class="primary compact" :disabled="saving" @click="save"><Save :size="16"/>保存新版本</button></div></header><div class="ppt-workspace"><aside class="slide-list"><button v-for="(s,i) in current.slideJson.slides" :key="s.id" :class="{selected:i===slideIndex}" @click="slideIndex=i;selected=null"><span>{{i+1}}</span><div class="mini-slide"><div v-for="el in s.elements" :key="el.id" class="mini-element" :style="{left:`${el.x/13.333*100}%`,top:`${el.y/7.5*100}%`,width:`${el.w/13.333*100}%`,height:`${el.h/7.5*100}%`,color:`#${el.color}`,background:el.type==='shape'?`#${el.fill??'EDE9FE'}`:'transparent'}">{{el.type==='text'?el.text:''}}</div></div></button></aside><main class="canvas-area"><div class="slide-canvas"><div v-for="el in slide?.elements" :key="el.id" :class="['slide-element',el.type,{selected:selected===el.id}]" :style="{left:`${el.x/13.333*100}%`,top:`${el.y/7.5*100}%`,width:`${el.w/13.333*100}%`,height:`${el.h/7.5*100}%`,fontSize:`${el.fontSize}px`,color:`#${el.color}`,background:el.type==='shape'?`#${el.fill??'EDE9FE'}`:'transparent',fontWeight:el.bold?'700':'400'}" @click.stop="selected=el.id"><textarea v-if="el.type==='text'" v-model="el.text"/></div></div></main><aside class="property-panel"><template v-if="slide?.elements.find(e=>e.id===selected)"><h3><Type :size="16"/> 元素属性</h3><label>文字<textarea v-model="slide!.elements.find(e=>e.id===selected)!.text"/></label><label>字号<input v-model.number="slide!.elements.find(e=>e.id===selected)!.fontSize" type="number" min="8" max="72"/></label><label>颜色<input v-model="slide!.elements.find(e=>e.id===selected)!.color"/></label><div class="field-grid"><label>X<input v-model.number="slide!.elements.find(e=>e.id===selected)!.x" type="number" step=".1"/></label><label>Y<input v-model.number="slide!.elements.find(e=>e.id===selected)!.y" type="number" step=".1"/></label><label>宽<input v-model.number="slide!.elements.find(e=>e.id===selected)!.w" type="number" step=".1"/></label><label>高<input v-model.number="slide!.elements.find(e=>e.id===selected)!.h" type="number" step=".1"/></label></div></template><p v-else class="muted">选择画布元素后编辑属性</p><hr/><h3>历史版本</h3><button v-for="v in data.versions" :key="v.id" :class="['version',{active:v.id===current.id}]" @click="selectVersion(v)">版本 {{v.version}}<small>{{new Date(v.createdAt).toLocaleString()}}</small></button></aside></div></div>
</template>
