<script setup lang="ts">
import { onMounted, ref } from "vue"; import { api } from "../api"; import { CheckCircle2, Circle, Pencil, Trash2 } from "lucide-vue-next";
type Todo={id:string;title:string;description:string;owner:string;dueAt?:string;status:string;meeting:{title:string}};
const todos=ref<Todo[]>([]); const status=ref(""); const owner=ref(""); const dueFrom=ref(""); const dueTo=ref(""); const loading=ref(false);
async function load(){loading.value=true;try{const q=new URLSearchParams();if(status.value)q.set("status",status.value);if(owner.value)q.set("owner",owner.value);if(dueFrom.value)q.set("dueFrom",dueFrom.value);if(dueTo.value)q.set("dueTo",dueTo.value);todos.value=await api(`/todos?${q}`);}finally{loading.value=false;}}
async function update(todo:Todo, patch:any){await api(`/todos/${todo.id}`,{method:"PATCH",body:JSON.stringify(patch)});await load();}
async function edit(todo:Todo){const title=prompt("待办标题",todo.title);if(!title)return;const description=prompt("事项说明",todo.description);if(description===null)return;const ownerValue=prompt("责任人",todo.owner);if(!ownerValue)return;const due=prompt("截止时间（ISO 格式或留空表示待确认）",todo.dueAt??"");if(due===null)return;await update(todo,{title,description,owner:ownerValue,dueAt:due?new Date(due).toISOString():null});}
async function remove(id:string){if(confirm("确认删除该待办？")){await api(`/todos/${id}`,{method:"DELETE"});await load();}}
onMounted(load);
</script>
<template><div class="page"><header class="page-header"><div><h1>待办中心</h1><p>集中处理会议中自动识别的承诺闭环事项</p></div></header><div class="filters"><select v-model="status" @change="load"><option value="">全部状态</option><option value="PENDING">待处理</option><option value="IN_PROGRESS">进行中</option><option value="COMPLETED">已完成</option><option value="CANCELLED">已取消</option></select><input v-model="owner" placeholder="筛选责任人" @keyup.enter="load"/><input v-model="dueFrom" type="date" title="截止日期起"/><input v-model="dueTo" type="date" title="截止日期止"/><button @click="load">筛选</button></div><div class="list-card"><div v-if="loading" class="muted">加载中…</div><div v-else-if="!todos.length" class="empty-list">暂无待办</div><article v-for="todo in todos" :key="todo.id" class="todo-row"><button class="status-icon" @click="update(todo,{status:todo.status==='COMPLETED'?'PENDING':'COMPLETED'})"><CheckCircle2 v-if="todo.status==='COMPLETED'"/><Circle v-else/></button><div class="todo-main"><strong>{{todo.title}}</strong><p>{{todo.description}}</p><small>{{todo.meeting.title}} · 责任人：{{todo.owner}} · 截止：{{todo.dueAt?new Date(todo.dueAt).toLocaleString():'待确认'}}</small></div><select :value="todo.status" @change="update(todo,{status:($event.target as HTMLSelectElement).value})"><option value="PENDING">待处理</option><option value="IN_PROGRESS">进行中</option><option value="COMPLETED">已完成</option><option value="CANCELLED">已取消</option></select><button class="icon" title="编辑" @click="edit(todo)"><Pencil :size="17"/></button><button class="icon danger" @click="remove(todo.id)"><Trash2 :size="17"/></button></article></div></div></template>
